### ISSUE TITLE
Implement verify file hashes with rpm task

### ISSUE THREAD

**Issue by jason-callaway** [fedoraredteam/compliant#498]
Implement task at [tasks/system_settings/installing_and_maintaining_software/updating_software/redhat.yml](https://github.com/fedoraredteam/compliant/blob/master/tasks/system_settings/installing_and_maintaining_software/updating_software/redhat.yml#L15)

**Comment by patrickmryan** [comment]
I'd like to take a stab at implementing this. Is there any guidance on whether or not I can implement this using Perl, a package that is not always installed by default?  Perl seems to be standard on RHEL but, as I learned the hard way, not in an EC2 image.  I could include a prerequisite task to ensure that the Perl package gets installed if it's not already there.

**Comment by jason-callaway** [comment]
+1

I think having a Perl implementation is better than none at all!

However, Python is always there, even on distributions like Atomic.

One approach could be to implement it in whatever language you're comfortable, then we would work together on translating it to Python.

**Comment by patrickmryan** [comment]
I'm going to try first to implement it purely in Ansible. I just need to get a handle on how to iterate over a collection of results from task to task.

**Comment by jason-callaway** [comment]
Sounds good to me. Let me know if you need help. The debug module is your friend! :)

Sorry about the accidental closure, BTW. Ran the wrong Python program...

**Comment by patrickmryan** [comment]
I figured it out.  PR coming soon.
